# https://github.com/django/djangoproject.com

services:
  db:
    image: postgis/postgis:14-3.3-alpine
    env_file:
      - env/postgis.dev.env
    ports:
      - "5432:5432" # To access database on localhost if needed (pgadmin...)
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - env/postgis.dev.env
      - env/django.dev.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
