# Generated by Django 4.1.3 on 2022-11-06 13:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("coordinates", django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="MountainPeak",
            fields=[
                (
                    "location_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mountain_peaks.location",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Mountain's peak name")),
                ("altitude", models.IntegerField()),
            ],
            bases=("mountain_peaks.location",),
        ),
    ]
