# Generated by Django 4.1.3 on 2022-11-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Mountain's name")),
                ('coordinates', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
