# Generated by Django 4.1.3 on 2022-11-05 15:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Mountain's name")),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitude', models.IntegerField()),
            ],
        ),
    ]
