# Generated by Django 4.1.3 on 2022-11-05 16:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_peaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
