# Generated by Django 4.1.3 on 2022-11-05 16:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_peaks', '0002_alter_mountain_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MountainPeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Mountain's peak name")),
                ('altitude', models.IntegerField()),
                ('coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mountain_peaks.coordinate')),
            ],
        ),
        migrations.DeleteModel(
            name='Mountain',
        ),
    ]
