# Generated by Django 4.1.3 on 2022-11-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_peaks', '0003_coordinate_mountainpeak_delete_mountain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordinate',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='mountainpeak',
            old_name='coordinates',
            new_name='location',
        ),
    ]
